const Q = (id, d, clue, answer, teen) => ({
  id,
  d,
  clue,
  answer,
  teen: teen !== undefined ? teen : d === 'easy',
});

const CATEGORY_POOL = [
  'THE BÁB',
  "BAHÁ'U'LLÁH",
  "'ABDU'L-BAHÁ",
  'HOLY PLACES',
  'THE WRITINGS',
  'PRINCIPLES & TEACHINGS',
  'SHOGHI EFFENDI',
  'HISTORY & EVENTS',
  "BAHA'I CALENDAR",
  'HANDS OF THE CAUSE',
  'INSTITUTIONS',
  'PERSECUTION & RESILIENCE',
];

const QUESTION_BANK = {
  'THE BÁB': [
    Q('bab-e01', 'easy', 'On May 23, 1844, the Báb declared in Iran that He was a Messenger of God—and Bahá\'ís celebrate that holy day every year.', 'What is the Declaration of the Báb?'),
    Q('bab-e02', 'easy', 'The Báb was born in Shiraz, a city in this country where Bahá\'ís have made pilgrimage for generations.', 'What is Iran?'),
    Q('bab-e03', 'easy', 'The title "Báb" means "the Gate" in this language.', 'What is Arabic?'),
    Q('bab-e04', 'easy', 'The Báb taught that He had come to prepare the world for a greater Prophet whose name means "Glory of God."', 'Who is Bahá\'u\'lláh?'),
    Q('bab-e05', 'easy', 'The Báb\'s golden-domed Shrine, visited by Bahá\'ís from every country, stands on Mount Carmel in this city.', 'What is Haifa?'),
    Q('bab-e06', 'easy', 'The Báb\'s public mission lasted only six years, from 1844 until His martyrdom in this year.', 'What is 1850?'),
    Q('bab-e07', 'easy', 'The Báb was executed by firing squad in this northwestern Iranian city in 1850.', 'What is Tabriz?'),
    Q('bab-e08', 'easy', 'The Báb\'s followers were first called Bábís, and His teachings eventually gave rise to this world religion.', 'What is the Bahá\'í Faith?'),
    Q('bab-e09', 'easy', 'The Báb chose eighteen disciples as Letters of the Living, plus His first believer—for this total number of early heroes.', 'What is nineteen?'),
    Q('bab-e10', 'easy', 'Bahá\'ís believe the Báb opened the way for the Founder of the Bahá\'í Faith, whose title means "Glory of God."', 'Who is Bahá\'u\'lláh?'),
    Q('bab-e11', 'easy', 'The Báb revealed a calendar with 19 months of 19 days—the same calendar Bahá\'ís use today.', 'What is the Bahá\'í calendar?'),
    Q('bab-e12', 'easy', 'The Báb\'s golden dome is one of the most recognizable landmarks in Haifa, in this country.', 'What is Israel?'),
    Q('bab-m01', 'medium', 'On May 23, 1844, this young scholar from Khurásán became the Báb\'s first believer and a Letter of the Living.', 'Who is Mullá Husayn?'),
    Q('bab-m02', 'medium', 'After Máh-Kú, the Báb was transferred to this second mountain fortress.', 'What is Chihríq?'),
    Q('bab-m03', 'medium', 'The Báb\'s principal book of laws and teachings is called this.', 'What is the Bayán?'),
    Q('bab-m04', 'medium', 'This courageous poet and scholar, also called Qurratu\'l-\'Ayn, was among the Letters of the Living.', 'Who is Táhirih?'),
    Q('bab-m05', 'medium', 'Mullá Muhammad-\'Alí of Bárfurúsh, a Letter of the Living, is commonly known by this title.', 'Who is Quddús?'),
    Q('bab-m06', 'medium', 'The Persian prime minister known as the Amír-Nizám ordered the Báb\'s execution.', 'Who is Mírzá Taqí Khán?'),
    Q('bab-m07', 'medium', 'The Báb declared His mission to Mullá Husayn on the evening before May 23, 1844 — a date Bahá\'ís celebrate every year as this holy day.', 'What is the Declaration of the Báb?'),
    Q('bab-m08', 'medium', 'The Báb\'s remains were finally interred on Mount Carmel in this year.', 'What is 1909?'),
    Q('bab-m09', 'medium', 'This Letter of the Living from Zanján led the heroic defense of his city.', 'Who is Hujjat?'),
    Q('bab-m10', 'medium', 'Mullá Sádiq-i-Khurásání, among the first believers in Isfahan, was later titled Ismu\'lláhu\'l-Asdaq by Bahá\'u\'lláh.', 'Who is Ismu\'lláhu\'l-Asdaq?'),
    Q('bab-m11', 'medium', 'Bábís under Mullá Husayn defended this shrine-fortress in 1848–1849.', 'What is Shaykh Tabarsí?'),
    Q('bab-m12', 'medium', 'At this 1848 conference, Táhirih appeared unveiled and proclaimed a new Day.', 'What is Badasht?'),
    Q('bab-h01', 'hard', 'The Báb\'s father, a merchant of Shiraz, was named this.', 'Who is Mírzá Muhammad Ridá?'),
    Q('bab-h02', 'hard', 'The Báb\'s mother was known by this name.', 'Who is Fátimih Bagum?'),
    Q('bab-h03', 'hard', 'This celebrated ode in 127 verses is among the Báb\'s best-known poetic works.', 'What is the Qasídiy-i-Dhahabiyyih?'),
    Q('bab-h04', 'hard', 'On July 9, 1850, the first attempt to execute the Báb with 750 soldiers failed when the bullets cut only these.', 'What are the ropes binding Him?'),
    Q('bab-h05', 'hard', 'This uncle of the Báb raised Him after His father\'s death and is titled Khál-i-A\'zam (Most Great Uncle).', 'Who is Hájí Mírzá Siyyid \'Alí?'),
    Q('bab-h06', 'hard', 'The Báb\'s epistle to Muhammad Sháh, outlining the proofs of His mission, is called this.', 'What is the Dalá\'il-i-Sab\'ih (Seven Proofs)?'),
    Q('bab-h07', 'hard', 'Mullá Muhammad-\'Alí of Bárfurúsh, one of the Letters of the Living, is honored by the title Quddús, meaning this.', 'What is "the Most Holy"?'),
    Q('bab-h08', 'hard', 'Seven Bábís were executed on February 2, 1850, at this location in Tehran.', 'What is the Sabzih-Maydán?'),
    Q('bab-h09', 'hard', 'Half-brother of Bahá\'u\'lláh, he was appointed by the Báb as nominal leader and later opposed Bahá\'u\'lláh.', 'Who is Mírzá Yahyá (Subh-i-Azal)?'),
    Q('bab-h10', 'hard', 'The Báb revealed the Persian Bayán in nine chapters called these.', 'What are váhids?'),
    Q('bab-h11', 'hard', 'This Bábí martyr, titled Jináb-i-Básir, was executed in Baghdad in 1852.', 'Who is Siyyid Ismá\'íl of Zavárih?'),
    Q('bab-h12', 'hard', '\'Abdu\'l-Bahá transferred the Báb\'s remains from Tehran to the Holy Land beginning in this year.', 'What is 1899?'),
  ],
  "BAHÁ'U'LLÁH": [
    Q('buh-e01', 'easy', 'In 1863, in a garden near Baghdad, Bahá\'u\'lláh announced He was God\'s Messenger for a new age—Bahá\'ís celebrate this festival as Riḍván.', 'What is Riḍván?'),
    Q('buh-e02', 'easy', 'Bahá\'u\'lláh\'s holiest Shrine, where Bahá\'ís turn in prayer, is located at Bahjí near this city in Israel.', 'What is \'Akká?'),
    Q('buh-e03', 'easy', 'Revealed near \'Akká, Bahá\'u\'lláh\'s Most Holy Book sets forth the laws and ordinances of His Faith.', 'What is the Kitáb-i-Aqdas?'),
    Q('buh-e04', 'easy', 'At devotionals and camps, Bahá\'í youth often read from this beloved collection of short passages that begin "O Son of Spirit!"', 'What are the Hidden Words?'),
    Q('buh-e05', 'easy', 'Bahá\'u\'lláh taught that Judaism, Christianity, Islam, and other faiths all come from the same God—the oneness of this.', 'What is religion?'),
    Q('buh-e06', 'easy', 'Bahá\'u\'lláh spent His final years near the prison city of \'Akká in this modern country.', 'What is Israel?'),
    Q('buh-e07', 'easy', 'In His Will, Bahá\'u\'lláh named His eldest son to lead the Bahá\'í Faith after Him.', 'Who is \'Abdu\'l-Bahá?'),
    Q('buh-e08', 'easy', 'Bahá\'u\'lláh passed away at Bahjí in this year, a holy day on the Bahá\'í calendar.', 'What is 1892?'),
    Q('buh-e09', 'easy', 'Bahá\'u\'lláh taught that men and women are equal—like the two wings of a bird, both are needed for society to advance.', 'What is equality?'),
    Q('buh-e10', 'easy', 'Bahá\'u\'lláh was born in Tehran, the capital of this country, before years of exile and imprisonment.', 'What is Iran?'),
    Q('buh-e11', 'easy', 'Bahá\'u\'lláh revealed three daily prayers—short, medium, and long—that Bahá\'ís recite as the Obligatory these.', 'What are the Obligatory Prayers?'),
    Q('buh-e12', 'easy', 'The title Bahá\'u\'lláh means "Glory of God" in this language.', 'What is Arabic?'),
    Q('buh-m01', 'medium', 'Bahá\'u\'lláh received His first intimations of Revelation in the Síyáh-Chál, meaning this.', 'What is the Black Pit?'),
    Q('buh-m02', 'medium', 'This epistle to a Kurdish chieftain was among Bahá\'u\'lláh\'s last major works.', 'What is the Epistle to the Son of the Wolf?'),
    Q('buh-m03', 'medium', 'Bahá\'u\'lláh addressed letters to the rulers of Europe and the Middle East collectively called these.', 'What are the Tablets to the Kings?'),
    Q('buh-m04', 'medium', 'In 1868, Bahá\'u\'lláh and His family were banished across the Mediterranean to the prison city of \'Akká.', 'What is \'Akká?'),
    Q('buh-m05', 'medium', 'Before moving to the Mansion of Bahjí, Bahá\'u\'lláh spent about two years at a nearby country house called Mazra\'ih in this prison city.', 'What is \'Akká?'),
    Q('buh-m06', 'medium', 'Bahá\'u\'lláh\'s tablet to Napoleon III was later compiled as one of the tablets within this larger work.', 'What is the Súriy-i-Haykal?'),
    Q('buh-m07', 'medium', 'Bahá\'u\'lláh revealed the Hidden Words in Arabic and this language.', 'What is Persian?'),
    Q('buh-m08', 'medium', 'The Seven Valleys describes the soul\'s journey using imagery from this Persian poet\'s Conference of the Birds.', 'Who is Attar?'),
    Q('buh-m09', 'medium', 'Bahá\'u\'lláh was exiled from Tehran to Baghdad in this year.', 'What is 1853?'),
    Q('buh-m10', 'medium', 'This half-brother of Bahá\'u\'lláh was appointed nominal leader by the Báb and later opposed Him.', 'Who is Mírzá Yahyá (Subh-i-Azal)?'),
    Q('buh-m11', 'medium', 'Bahá\'u\'lláh designated \'Abdu\'l-Bahá as the sole interpreter of His Writings and Head of the Faith.', 'What is the Center of the Covenant?'),
    Q('buh-m12', 'medium', 'Bahá\'u\'lláh revealed the Tablet of Carmel on Mount Carmel in this year.', 'What is 1891?'),
    Q('buh-h01', 'hard', 'Bahá\'u\'lláh\'s father, a minister at the court of Fath-\'Alí Sháh, was known by this title.', 'Who is Mírzá Buzurg?'),
    Q('buh-h02', 'hard', 'Bahá\'u\'lláh bestowed the title Ghusn-i-A\'zam (Most Great Branch) upon this son in the Kitáb-i-\'Ahd.', 'Who is \'Abdu\'l-Bahá?'),
    Q('buh-h03', 'hard', 'Bahá\'u\'lláh revealed the Kitáb-i-Aqdas in this city around 1873.', 'What is \'Akká?'),
    Q('buh-h04', 'hard', 'The attempt on the life of Násiri\'d-Dín Sháh in 1852 led to the imprisonment of Bahá\'u\'lláh in this dungeon.', 'What is the Síyáh-Chál?'),
    Q('buh-h05', 'hard', 'This Bábí follower attempted to assassinate Násiri\'d-Dín Sháh in 1852.', 'Who is Sádiq-i-Tabrízí?'),
    Q('buh-h06', 'hard', 'Bahá\'u\'lláh\'s mystical treatise paired with The Seven Valleys is called this.', 'What is The Four Valleys?'),
    Q('buh-h07', 'hard', 'The Lawh-i-Maqsúd is addressed to this Hand of the Cause and outstanding scholar.', 'Who is Hájí Mírzá Haydar-\'Alí?'),
    Q('buh-h08', 'hard', 'Bahá\'u\'lláh revealed the Súriy-i-Ra\'ís in response to the exile decree of this Ottoman official.', 'Who is \'Álí Páshá (the Grand Vizier)?'),
    Q('buh-h09', 'hard', 'The Kitáb-i-Íqán was revealed in Baghdad partly in answer to questions from this maternal uncle of the Báb.', 'Who is Hájí Mírzá Siyyid Muhammad (the "Uncle")?'),
    Q('buh-h10', 'hard', 'Bahá\'u\'lláh\'s daughter, known for her piety and learning, was named this.', 'Who is Bahíyyih Khánum?'),
    Q('buh-h11', 'hard', 'This tablet announces the establishment of the Universal House of Justice.', 'What is the Tablet of Ishráqát?'),
    Q('buh-h12', 'hard', 'Bahá\'u\'lláh passed away at the Mansion of Bahjí in this year and was buried in the Shrine there.', 'What is 1892?'),
  ],
  "'ABDU'L-BAHÁ": [
    Q('abd-e01', 'easy', '\'Abdu\'l-Bahá lived most of His life near \'Akká and later in this city on Mount Carmel, where He passed away in 1921.', 'What is Haifa?'),
    Q('abd-e02', 'easy', 'In 1912, \'Abdu\'l-Bahá traveled by train across this country, speaking in more than 40 cities from coast to coast.', 'What is the United States?'),
    Q('abd-e03', 'easy', 'During His 1911 trip to Europe, \'Abdu\'l-Bahá gave talks in London and in this capital city of France.', 'What is Paris?'),
    Q('abd-e04', 'easy', '\'Abdu\'l-Bahá was born in this city, the capital of Iran, on May 23, 1844.', 'What is Tehran?'),
    Q('abd-e05', 'easy', 'For organizing famine relief during World War I, Britain honored \'Abdu\'l-Bahá with a knighthood in this year.', 'What is 1920?'),
    Q('abd-e06', 'easy', 'In His Will, \'Abdu\'l-Bahá appointed His grandson to serve as Guardian of the Bahá\'í Faith after Him.', 'Who is Shoghi Effendi?'),
    Q('abd-e07', 'easy', 'During World War I, \'Abdu\'l-Bahá wrote detailed letters to the Bahá\'ís of North America about spreading the Faith to every part of the world.', 'What are the Tablets of the Divine Plan?'),
    Q('abd-e08', 'easy', '\'Abdu\'l-Bahá spent forty years as a prisoner in the walled city of \'Akká before being freed in 1908.', 'What is \'Akká?'),
    Q('abd-e09', 'easy', '\'Abdu\'l-Bahá passed away in Haifa in this year, mourned by thousands of people of every background.', 'What is 1921?'),
    Q('abd-e10', 'easy', 'The title \'Abdu\'l-Bahá means "Servant of Glory" in this language.', 'What is Arabic?'),
    Q('abd-e11', 'easy', 'In 1912, \'Abdu\'l-Bahá laid the cornerstone of the first Bahá\'í House of Worship in America, in Wilmette in this state.', 'What is Illinois?'),
    Q('abd-e12', 'easy', '\'Abdu\'l-Bahá was buried in the Shrine of the Báb on Mount Carmel in this city in Israel.', 'What is Haifa?'),
    Q('abd-m01', 'medium', 'This Covenant-breaker, \'Abdu\'l-Bahá\'s half-brother, challenged His authority for decades.', 'Who is Mírzá Muhammad-\'Alí?'),
    Q('abd-m02', 'medium', '\'Abdu\'l-Bahá was imprisoned within the walls of \'Akká for this many years.', 'What is forty years?'),
    Q('abd-m03', 'medium', 'The Young Turk Revolution in 1908 ended decades of confinement for \'Abdu\'l-Bahá in this prison city.', 'What is \'Akká?'),
    Q('abd-m04', 'medium', 'This woman, titled Mother of the Faithful, was \'Abdu\'l-Bahá\'s wife.', 'Who is Munirih Khánum?'),
    Q('abd-m05', 'medium', '\'Abdu\'l-Bahá\'s funeral in Haifa drew mourners from every class and religion across this region.', 'What is Palestine?'),
    Q('abd-m06', 'medium', 'The Secret of Divine Civilization is \'Abdu\'l-Bahá\'s open letter about modernizing his native country, today called this.', 'What is Iran?'),
    Q('abd-m07', 'medium', 'At Howard University in 1912, \'Abdu\'l-Bahá spoke on the elimination of this social evil.', 'What is racial prejudice?'),
    Q('abd-m08', 'medium', 'Some Answered Questions records \'Abdu\'l-Bahá\'s explanations to this pilgrim from New York.', 'Who is Laura Clifford Barney?'),
    Q('abd-m09', 'medium', '\'Abdu\'l-Bahá revealed the Tablets of the Divine Plan during World War I, primarily to the Bahá\'ís of this country.', 'What is the United States?'),
    Q('abd-m10', 'medium', '\'Abdu\'l-Bahá\'s book The Promulgation of Universal Peace collects addresses He gave during His travels to Europe and North America through this year.', 'What is 1913?'),
    Q('abd-m11', 'medium', '\'Abdu\'l-Bahá laid the cornerstone of the House of Worship in this Chicago suburb in 1912.', 'What is Wilmette?'),
    Q('abd-m12', 'medium', 'The Master\'s visit to the Lake Mohonk Peace Conference addressed the cause of this.', 'What is international peace?'),
    Q('abd-h01', 'hard', 'This Covenant-breaker, a son of Bahá\'u\'lláh, forged documents to challenge \'Abdu\'l-Bahá.', 'Who is Mírzá Muhammad-\'Alí?'),
    Q('abd-h02', 'hard', '\'Abdu\'l-Bahá\'s younger brother, titled Ghusn-i-Athar (the Purest Branch), was named this.', 'Who is Mírzá Mihdí?'),
    Q('abd-h03', 'hard', 'Mírzá Mihdí, the Purest Branch, died at age 20 after falling from this structure in \'Akká.', 'What is the roof (of the prison barracks)?'),
    Q('abd-h04', 'hard', 'The Ottoman authorities investigated \'Abdu\'l-Bahá in 1907 through a commission led by this official.', 'Who is \'Arif Hikmat Bey?'),
    Q('abd-h05', 'hard', 'Shoghi Effendi married Mary Maxwell, daughter of May Maxwell and William Sutherland Maxwell, who became known as this.', 'Who is Rúhíyyih Khánum?'),
    Q('abd-h06', 'hard', 'The Tablet to The Hague was \'Abdu\'l-Bahá\'s response to an organization promoting this.', 'What is international arbitration?'),
    Q('abd-h07', 'hard', 'This pilgrim\'s notes of \'Abdu\'l-Bahá\'s words became "Some Answered Questions."', 'Who is Laura Clifford Barney?'),
    Q('abd-h08', 'hard', '\'Abdu\'l-Bahá sent this Hand of the Cause to teach the Faith in Latin America.', 'Who is Martha Root?'),
    Q('abd-h09', 'hard', 'The second and third parts of \'Abdu\'l-Bahá\'s Will and Testament were written in this year.', 'What is 1921?'),
    Q('abd-h10', 'hard', '\'Abdu\'l-Bahá\'s talk at Stanford University in 1912 addressed the harmony of these two fields.', 'What are science and religion?'),
    Q('abd-h11', 'hard', 'This early American believer hosted \'Abdu\'l-Bahá in New York and painted His portrait; her interviews became Some Answered Questions.', 'Who is Laura Clifford Barney?'),
    Q('abd-h12', 'hard', '\'Abdu\'l-Bahá designated the region from which the Universal House of Justice would emerge as this.', 'What is the Holy Land?'),
  ],
  'HOLY PLACES': [
    Q('hpl-e01', 'easy', 'The holiest site for Bahá\'ís is the Shrine of Bahá\'u\'lláh at Bahjí, near this city in Israel.', 'What is \'Akká?'),
    Q('hpl-e02', 'easy', 'The golden-domed Shrine of the Báb, with its terraced gardens, overlooks this city on Mount Carmel.', 'What is Haifa?'),
    Q('hpl-e03', 'easy', 'The first Bahá\'í House of Worship in the United States stands in Wilmette, in this state.', 'What is Illinois?'),
    Q('hpl-e04', 'easy', 'The famous lotus-shaped House of Worship in India is located in this capital city.', 'What is New Delhi?'),
    Q('hpl-e05', 'easy', 'The Seat of the Universal House of Justice sits on Mount Carmel in this city.', 'What is Haifa?'),
    Q('hpl-e06', 'easy', 'The Báb was born in Shiraz, a city in this country.', 'What is Iran?'),
    Q('hpl-e07', 'easy', 'In 1863, Bahá\'u\'lláh declared His mission in a garden near Baghdad; Bahá\'ís celebrate this spring festival as Riḍván.', 'What is Riḍván?'),
    Q('hpl-e08', 'easy', 'Bahá\'ís refer to Israel and its surroundings—home to the Shrines of the Báb and Bahá\'u\'lláh—as this.', 'What is the Holy Land?'),
    Q('hpl-e09', 'easy', 'Many Bahá\'í youth dream of visiting the gardens and Shrines on Mount Carmel in this country.', 'What is Israel?'),
    Q('hpl-e10', 'easy', 'Bahá\'u\'lláh lived for years as a prisoner in the walled city of \'Akká, on the coast of this sea.', 'What is the Mediterranean Sea?'),
    Q('hpl-e11', 'easy', 'The House of Worship in Wilmette, Illinois, has nine sides—a design found in every continental Bahá\'í temple.', 'What is nine?'),
    Q('hpl-e12', 'easy', 'Pilgrims walking the 19 terraces on Mount Carmel are approaching the Shrine of this Herald of the Bahá\'í Faith.', 'Who is the Báb?'),
    Q('hpl-m01', 'medium', 'The Mansion of Bahjí was originally built by this Ottoman governor.', 'Who is \'Abdu\'lláh Páshá?'),
    Q('hpl-m02', 'medium', 'Bahá\'u\'lláh was confined in the barracks of the citadel of \'Akká for this many years.', 'What is two years?'),
    Q('hpl-m03', 'medium', 'The International Archives Building on Mount Carmel was designed under the direction of this Guardian.', 'Who is Shoghi Effendi?'),
    Q('hpl-m04', 'medium', 'The House of the Báb in Shiraz was destroyed in 1979 during unrest following this event.', 'What is the Islamic Revolution in Iran?'),
    Q('hpl-m05', 'medium', 'Bahá\'u\'lláh lived at the house of Mazra\'ih for about two years before moving to this nearby mansion.', 'What is Bahjí?'),
    Q('hpl-m06', 'medium', 'The Shrine of the Báb was completed under the direction of \'Abdu\'l-Bahá and this architect.', 'Who is William Sutherland Maxwell?'),
    Q('hpl-m07', 'medium', 'The House of \'Abbúd in \'Akká is where Bahá\'u\'lláh revealed many tablets including parts of this holy book.', 'What is the Kitáb-i-Aqdas?'),
    Q('hpl-m08', 'medium', 'The first Mashriqu\'l-Adhkár in \'Ishqábád was in this present-day country.', 'What is Turkmenistan?'),
    Q('hpl-m09', 'medium', 'The Báb was imprisoned at Máh-Kú and Chihríq in northwestern Iran, in the region known as this.', 'What is Azerbaijan?'),
    Q('hpl-m10', 'medium', 'The resting place of \'Abdu\'l-Bahá is within the Shrine of the Báb on this mountain.', 'What is Mount Carmel?'),
    Q('hpl-m11', 'medium', 'The House of Worship in Kampala serves the Bahá\'ís of this continent.', 'What is Africa?'),
    Q('hpl-m12', 'medium', 'The International Teaching Centre building on the Arc was completed in this year.', 'What is 2000?'),
    Q('hpl-h01', 'hard', 'Bahá\'u\'lláh passed away in 1892 in a room within the Mansion of Bahjí, now part of this holiest Shrine in the Bahá\'í world.', 'What is the Shrine of Bahá\'u\'lláh?'),
    Q('hpl-h02', 'hard', 'For over half a century after His execution, believers secretly carried the Báb\'s remains until they were interred on Mount Carmel in 1909.', 'What is Mount Carmel?'),
    Q('hpl-h03', 'hard', 'The colonnade connecting the Shrine of the Báb to the Arc on Mount Carmel was completed in this decade.', 'What is the 1990s?'),
    Q('hpl-h04', 'hard', 'The House of Bahá\'u\'lláh in Adrianople (Edirne) is located in this present-day country.', 'What is Turkey?'),
    Q('hpl-h05', 'hard', 'Shoghi Effendi acquired the Mansion of Bahjí from this family in 1952.', 'Who is the Farah family?'),
    Q('hpl-h06', 'hard', 'The original House of Worship in \'Ishqábád was seized and later destroyed after this political change.', 'What is the Soviet Revolution?'),
    Q('hpl-h07', 'hard', 'The Monument Gardens on Mount Carmel contain the graves of members of this holy family.', 'Who is the family of Bahá\'u\'lláh?'),
    Q('hpl-h08', 'hard', 'The terraces of the Shrine of the Báb number this many, matching the months of the Bahá\'í calendar.', 'What is nineteen?'),
    Q('hpl-h09', 'hard', 'The House of Worship in Santiago, Chile, serves as the Mother Temple of this region.', 'What is South America?'),
    Q('hpl-h10', 'hard', 'Bahá\'u\'lláh was exiled from Adrianople to \'Akká in August of this year.', 'What is 1868?'),
    Q('hpl-h11', 'hard', 'The Pilgrim House on Haparsim Street in Haifa was built during the ministry of this Guardian.', 'Who is Shoghi Effendi?'),
    Q('hpl-h12', 'hard', 'The Qiblih was changed from the Shrine of the Báb to Bahjí upon the passing of Bahá\'u\'lláh in this year.', 'What is 1892?'),
  ],
  'THE WRITINGS': [
    Q('wri-e01', 'easy', 'Many Bahá\'í children memorize a short daily prayer that begins "I bear witness, O my God, that Thou hast created me to know Thee and to worship Thee…"', 'What is the Short Obligatory Prayer?'),
    Q('wri-e02', 'easy', 'At devotionals and camps, youth often read from this collection of short passages that begin "O Son of Spirit!"', 'What are the Hidden Words?'),
    Q('wri-e03', 'easy', 'Bahá\'u\'lláh\'s Most Holy Book of laws guides Bahá\'í life—from daily prayer to the annual Fast and Naw-Rúz.', 'What is the Kitáb-i-Aqdas?'),
    Q('wri-e04', 'easy', 'Bahá\'ís can choose among a short, medium, and long version when reciting one of these each day.', 'What is an Obligatory Prayer?'),
    Q('wri-e05', 'easy', 'Shoghi Effendi spent decades translating Bahá\'u\'lláh\'s Revelation into this language so believers worldwide could read it.', 'What is English?'),
    Q('wri-e06', 'easy', 'This document from \'Abdu\'l-Bahá named Shoghi Effendi as Guardian and described how the Faith would be led after Him.', 'What is the Will and Testament of \'Abdu\'l-Bahá?'),
    Q('wri-e07', 'easy', 'Bahá\'í families often keep a compilation of Bahá\'u\'lláh\'s prayers assembled by Shoghi Effendi called Prayers and this.', 'What is Meditations?'),
    Q('wri-e08', 'easy', 'The Kitáb-i-Aqdas tells Bahá\'ís to pray daily, observe a 19-day Fast, and celebrate their New Year at this spring festival.', 'What is Naw-Rúz?'),
    Q('wri-e09', 'easy', 'During the Fast, Bahá\'ís turn to prayer and reflection, often using the Long version of these.', 'What is the Obligatory Prayer?'),
    Q('wri-e10', 'easy', 'Bahá\'u\'lláh revealed three daily prayers of different lengths—short, medium, and long—collectively called these.', 'What are the Obligatory Prayers?'),
    Q('wri-e11', 'easy', 'The Tablets of the Divine Plan urge Bahá\'ís to carry the Faith to every nation—a message youth often encounter in Bahá\'í classes.', 'What are the Tablets of the Divine Plan?'),
    Q('wri-e12', 'easy', 'Laura Clifford Barney published the transcripts of her interviews with \'Abdu\'l-Bahá under this book title.', 'What is Some Answered Questions?'),
    Q('wri-m01', 'medium', 'The Kitáb-i-Ahd, meaning "Book of My Covenant," designates \'Abdu\'l-Bahá as this.', 'What is the Center of the Covenant?'),
    Q('wri-m02', 'medium', 'Bahá\'u\'lláh\'s Most Holy Book prescribes 19 days of fasting during this month.', 'What is \'Alá?'),
    Q('wri-m03', 'medium', 'This mystical treatise by Bahá\'u\'lláh is paired with The Seven Valleys.', 'What is The Four Valleys?'),
    Q('wri-m04', 'medium', 'The Epistle to the Son of the Wolf was addressed to a Kurdish chieftain named this.', 'Who is Najaf-Qulí?'),
    Q('wri-m05', 'medium', 'The Súriy-i-Haykal contains tablets addressed to individual rulers including Napoleon III and this Persian monarch.', 'Who is Násiri\'d-Dín Sháh?'),
    Q('wri-m06', 'medium', 'The Long Obligatory Prayer begins "O Thou Who art the Lord of all names and the Maker of the heavens!"', 'What is the Long Obligatory Prayer?'),
    Q('wri-m07', 'medium', 'The Summons of the Lord of Hosts includes tablets addressed to Napoleon III, Queen Victoria, and Czar Alexander II of this country.', 'What is Russia?'),
    Q('wri-m08', 'medium', 'The Báb\'s principal doctrinal work, revealed in Arabic and Persian, is called this.', 'What is the Bayán?'),
    Q('wri-m09', 'medium', 'Some Answered Questions is based on interviews conducted by Laura Clifford Barney with this Figure.', 'Who is \'Abdu\'l-Bahá?'),
    Q('wri-m10', 'medium', 'The Secret of Divine Civilization was written by \'Abdu\'l-Bahá as a letter to the Bahá\'ís of Persia, now called this.', 'What is Iran?'),
    Q('wri-m11', 'medium', 'Bahá\'u\'lláh revealed a prayer for the departed commonly recited at Bahá\'í funerals.', 'What is the Prayer for the Dead?'),
    Q('wri-m12', 'medium', 'The Advent of Divine Justice was written by Shoghi Effendi as a letter to the Bahá\'ís of this country.', 'What is the United States?'),
    Q('wri-h01', 'hard', 'The Kitáb-i-Íqán was revealed in Baghdad partly in response to questions from this uncle of the Báb.', 'Who is Hájí Mírzá Siyyid Muhammad?'),
    Q('wri-h02', 'hard', 'Bahá\'u\'lláh\'s Lawh-i-Sultán was revealed after His arrival in \'Akká and addressed to this Ottoman Sultan.', 'Who is \'Abdu\'l-\'Azíz?'),
    Q('wri-h03', 'hard', 'The Persian Bayán was revealed by the Báb in nine units called these.', 'What are váhids?'),
    Q('wri-h04', 'hard', 'The Tablet of Ahmad is among Bahá\'u\'lláh\'s most weighty tablets, revealed in this language.', 'What is Arabic?'),
    Q('wri-h05', 'hard', 'Shoghi Effendi\'s translations of Bahá\'u\'lláh\'s writings are considered the standard version in this language.', 'What is English?'),
    Q('wri-h06', 'hard', 'The Lawh-i-Maqsúd contains Bahá\'u\'lláh\'s exposition of the station of this Hand of the Cause.', 'Who is Hájí Mírzá Haydar-\'Alí?'),
    Q('wri-h07', 'hard', 'The Báb\'s Dalá\'il-i-Sab\'ih, or Seven Proofs, was addressed to this Persian monarch.', 'Who is Muhammad Sháh?'),
    Q('wri-h08', 'hard', 'The Dispensation of Bahá\'u\'lláh is Shoghi Effendi\'s letter explaining the stations of the Central Figures and this institution.', 'What is the Guardianship?'),
    Q('wri-h09', 'hard', 'Bahá\'u\'lláh\'s Tablet of the World (Lawh-i-Dunyá) addresses principles of governance and this concept.', 'What is a world commonwealth?'),
    Q('wri-h10', 'hard', 'The Kitáb-i-Aqdas was supplemented by Questions and Answers revealed to this compiler.', 'Who is Zaynu\'l-Muqarrabín?'),
    Q('wri-h11', 'hard', '\'Abdu\'l-Bahá\'s Will and Testament was written in three parts between 1901 and this year.', 'What is 1921?'),
    Q('wri-h12', 'hard', 'The Báb\'s Qasídiy-i-Dhahabiyyih is a poem of this many verses.', 'What is 127?'),
  ],
  'PRINCIPLES & TEACHINGS': [
    Q('prt-e01', 'easy', 'Bahá\'í youth learn that Judaism, Christianity, Islam, and other religions all come from the same God—the oneness of this.', 'What is religion?'),
    Q('prt-e02', 'easy', 'Bahá\'ís are encouraged to investigate truth for themselves rather than blindly follow others—independent investigation of this.', 'What is truth?'),
    Q('prt-e03', 'easy', 'From March 2 to 20, Bahá\'ís abstain from food and drink from sunrise to sunset during this annual period.', 'What is the Fast?'),
    Q('prt-e04', 'easy', 'Every five years, Bahá\'ís elect a nine-member body in Haifa to guide the worldwide community.', 'What is the Universal House of Justice?'),
    Q('prt-e05', 'easy', 'Bahá\'u\'lláh taught that honest work, done to help others, is a form of worshipping this.', 'What is God?'),
    Q('prt-e06', 'easy', 'Bahá\'ís believe every person on Earth is part of one family—the oneness of this.', 'What is humanity?'),
    Q('prt-e07', 'easy', 'Bahá\'u\'lláh said men and women are like the two wings of a bird—society needs both to achieve this between the sexes.', 'What is equality?'),
    Q('prt-e08', 'easy', 'Right before the annual 19-day Fast, Bahá\'ís celebrate a short joyful period called Ayyám-i-Há.', 'What is Ayyám-i-Há?'),
    Q('prt-e09', 'easy', 'Rather than following priests or clergy, Bahá\'ís are taught to search for truth on their own—a principle called independent investigation of this.', 'What is truth?'),
    Q('prt-e10', 'easy', 'Bahá\'u\'lláh taught that racism, religious hatred, and every form of this must be eliminated.', 'What is prejudice?'),
    Q('prt-e11', 'easy', 'Every 19 days, Bahá\'í communities gather for prayer, consultation, and fellowship at the Nineteen Day this.', 'What is Feast?'),
    Q('prt-e12', 'easy', 'Bahá\'u\'lláh taught that both sons and daughters must be educated, because women are the first teachers of their children.', 'What is education?'),
    Q('prt-m01', 'medium', 'Bahá\'u\'lláh taught that humanity is currently in its collective stage of this — the final stage before maturity.', 'What is adolescence?'),
    Q('prt-m02', 'medium', 'Local and national spiritual assemblies are elected each year during this period.', 'What is Riḍván?'),
    Q('prt-m03', 'medium', 'Bahá\'ís turn toward Bahjí when reciting the Long Obligatory Prayer; this direction is called the Qiblih.', 'What is the Qiblih?'),
    Q('prt-m04', 'medium', 'Bahá\'u\'lláh taught that science and religion must agree, as both are expressions of this.', 'What is truth?'),
    Q('prt-m05', 'medium', 'The Bahá\'í teaching of progressive revelation means God sends Manifestations of God at intervals suited to the needs of this.', 'What is humanity?'),
    Q('prt-m06', 'medium', 'Bahá\'u\'lláh taught that decisions in Bahá\'í communities should be made through prayerful discussion called this.', 'What is consultation?'),
    Q('prt-m07', 'medium', 'Bahá\'u\'lláh taught that laws about inheritance help prevent extremes of wealth and this.', 'What is poverty?'),
    Q('prt-m08', 'medium', 'Bahá\'u\'lláh taught that education is obligatory for both sons and this.', 'What are daughters?'),
    Q('prt-m09', 'medium', 'The Bahá\'í principle of non-involvement in partisan politics reflects the Faith\'s commitment to this.', 'What is unity?'),
    Q('prt-m10', 'medium', 'Bahá\'u\'lláh taught that loyalty to one\'s government should not conflict with obedience to this.', 'What is God?'),
    Q('prt-m11', 'medium', 'The Bahá\'í Faith prohibits this practice, teaching that marriage should be monogamous.', 'What is polygamy?'),
    Q('prt-m12', 'medium', 'Bahá\'u\'lláh taught that everyone should learn a universal auxiliary language to help unite this.', 'What is humanity?'),
    Q('prt-h01', 'hard', 'Bahá\'u\'lláh taught that the sovereignty of the people should be recognized, but ultimate authority rests with this.', 'What is God?'),
    Q('prt-h02', 'hard', 'The Kitáb-i-Aqdas prescribes Huqúqu\'lláh, a spiritual obligation of giving this percentage of one\'s surplus.', 'What is nineteen percent?'),
    Q('prt-h03', 'hard', 'Bahá\'u\'lláh taught that the purpose of religion is to establish unity and this in the world.', 'What is order?'),
    Q('prt-h04', 'hard', 'The Bahá\'í teaching on the harmony of science and religion was elaborated by \'Abdu\'l-Bahá in talks at universities including this one in California.', 'What is Stanford University?'),
    Q('prt-h05', 'hard', 'Bahá\'u\'lláh wrote that "the earth is but one country, and mankind its citizens," calling for this kind of global order.', 'What is world unity?'),
    Q('prt-h06', 'hard', 'Bahá\'u\'lláh taught that speaking ill of someone behind their back — backbiting — is spiritually as harmful as this act.', 'What is murder?'),
    Q('prt-h07', 'hard', 'Bahá\'u\'lláh taught that Manifestations of God appear in a cycle of approximately this many years.', 'What is one thousand years?'),
    Q('prt-h08', 'hard', 'The Bahá\'í teaching on the elimination of extremes of wealth and poverty includes specific laws on this subject in the Kitáb-i-Aqdas.', 'What is inheritance?'),
    Q('prt-h09', 'hard', 'Bahá\'u\'lláh taught that true liberty is attained through submission to the Will of this.', 'What is God?'),
    Q('prt-h10', 'hard', 'Bahá\'ís avoid partisan political activity so they can work for unity above these kinds of divisions.', 'What are political divisions?'),
    Q('prt-h11', 'hard', 'Bahá\'u\'lláh taught that the education of girls is more important than that of boys because they will be the first educators of the next generation, called this.', 'What are mothers?'),
    Q('prt-h12', 'hard', 'The Bahá\'í teaching that religion must be the cause of love and fellowship condemns this when found in religious practice.', 'What is fanaticism?'),
  ],
  'SHOGHI EFFENDI': [
    Q('she-e01', 'easy', 'After \'Abdu\'l-Bahá passed away in 1921, His Will named His grandson to lead the Faith in an office called this.', 'What is the Guardianship?'),
    Q('she-e02', 'easy', 'Mary Maxwell of Montreal married the Guardian in 1937 and is known by this title.', 'Who is Rúhíyyih Khánum?'),
    Q('she-e03', 'easy', 'Shoghi Effendi translated Bahá\'u\'lláh\'s writings into this language.', 'What is English?'),
    Q('she-e04', 'easy', 'Shoghi Effendi built beautiful garden terraces on Mount Carmel in this city.', 'What is Haifa?'),
    Q('she-e05', 'easy', 'Shoghi Effendi passed away in London in this year.', 'What is 1957?'),
    Q('she-e06', 'easy', 'After Shoghi Effendi\'s passing, nine Hands of the Cause formed a body called the Custodians to guide the Faith.', 'What are the Custodians?'),
    Q('she-e07', 'easy', 'Under the Guardian\'s direction, the golden dome of the Shrine of the Báb and the Arc buildings were completed on Mount Carmel in this city.', 'What is Haifa?'),
    Q('she-e08', 'easy', 'Nabil\'s epic narrative of the early Bábí heroes was published in English under this dramatic title.', 'What is The Dawn-Breakers?'),
    Q('she-e09', 'easy', 'Shoghi Effendi served as Guardian from 1921 to 1957 — about this many years.', 'What is 36 years?'),
    Q('she-e10', 'easy', 'The Guardian organized the Bahá\'í world into elected local and national bodies called Spiritual these.', 'What are Assemblies?'),
    Q('she-e11', 'easy', 'Shoghi Effendi\'s single-volume history covers the first century of the Bahá\'í era, from the Báb to 1944.', 'What is God Passes By?'),
    Q('she-e12', 'easy', 'Shoghi Effendi was born in \'Akká in this year.', 'What is 1897?'),
    Q('she-m01', 'medium', 'Shoghi Effendi launched the Ten Year Crusade in this year.', 'What is 1953?'),
    Q('she-m02', 'medium', 'Shoghi Effendi coined the term "Arc" for the administrative buildings on the slope of Mount Carmel.', 'What is the Arc?'),
    Q('she-m03', 'medium', 'Shoghi Effendi\'s letters to the Bahá\'í world on administration were later collected in a volume titled Bahá\'í this.', 'What is Administration?'),
    Q('she-m04', 'medium', 'Shoghi Effendi translated Nabil\'s narrative into English as this book.', 'What is The Dawn-Breakers?'),
    Q('she-m05', 'medium', 'Shoghi Effendi described the period from 1944 to 1963 as a special era in Bahá\'í history spanning one full this.', 'What is century?'),
    Q('she-m06', 'medium', 'To protect the holiest Shrine, Shoghi Effendi purchased neighboring plots of land at Bahjí in this country.', 'What is Israel?'),
    Q('she-m07', 'medium', 'The Guardian\'s wife Rúhíyyih Khánum was the daughter of this Hand of the Cause.', 'Who is William Sutherland Maxwell?'),
    Q('she-m08', 'medium', 'Shoghi Effendi expanded the institution of Hands of the Cause, originally established by Bahá\'u\'lláh.', 'What are the Hands of the Cause?'),
    Q('she-m09', 'medium', 'Shoghi Effendi wrote The Advent of Divine Justice as a letter to the Bahá\'ís of this country.', 'What is the United States?'),
    Q('she-m10', 'medium', 'Shoghi Effendi described the World Order of Bahá\'u\'lláh as unfolding in two stages: the Administrative Order and this.', 'What is the World Commonwealth?'),
    Q('she-m11', 'medium', 'Shoghi Effendi is buried in the New Southgate Cemetery in this city.', 'What is London?'),
    Q('she-m12', 'medium', 'Shoghi Effendi raised the number of National Spiritual Assemblies from 26 to this number by 1957.', 'What is 56?'),
    Q('she-h01', 'hard', 'Shoghi Effendi studied at Balliol College in this university.', 'What is Oxford?'),
    Q('she-h02', 'hard', 'The unexpected death of Shoghi Effendi in 1957 led to these officers directing the Faith until 1963.', 'What are the Hands of the Cause?'),
    Q('she-h03', 'hard', 'Shoghi Effendi announced the formation of the first International Bahá\'í Council in a cable sent on January 9, 1951.', 'What is the International Bahá\'í Council?'),
    Q('she-h04', 'hard', 'Shoghi Effendi described two simultaneous world processes in his letters: the disintegration of the old order and this complementary process.', 'What is integration?'),
    Q('she-h05', 'hard', 'The Guardian described the Formative Age of the Faith as beginning with the passing of this Figure.', 'Who is \'Abdu\'l-Bahá?'),
    Q('she-h06', 'hard', 'Shoghi Effendi\'s Proclamation of Bahá\'u\'lláh was issued during the Holy Year commemorating the centenary of this event.', 'What is the Declaration of Bahá\'u\'lláh in the Garden of Ridván?'),
    Q('she-h07', 'hard', 'Shoghi Effendi appointed the first contingent of Hands of the Cause in this year.', 'What is 1951?'),
    Q('she-h08', 'hard', 'Shoghi Effendi\'s name means "the desired one" in this language.', 'What is Persian?'),
    Q('she-h09', 'hard', 'Shoghi Effendi described the Guardianship and the Universal House of Justice as the twin pillars of Bahá\'í this.', 'What is administration?'),
    Q('she-h10', 'hard', 'The International Bahá\'í Archives building was completed in this year under Shoghi Effendi\'s direction.', 'What is 1957?'),
    Q('she-h11', 'hard', 'Shoghi Effendi\'s cablegrams to the Bahá\'í world during World War II are collected in this volume.', 'What is Messages to the Bahá\'í World 1950–1957?'),
    Q('she-h12', 'hard', 'Shoghi Effendi had no children, and the line of hereditary Guardians ended with his passing because this condition was not met.', 'What is the appointment of a successor in his lifetime?'),
  ],
  'HISTORY & EVENTS': [
    Q('his-e01', 'easy', 'The Báb declared His mission in this year.', 'What is 1844?'),
    Q('his-e02', 'easy', 'Bahá\'u\'lláh declared His mission in the Garden of Ridván in this year.', 'What is 1863?'),
    Q('his-e03', 'easy', 'The Báb was executed in this year.', 'What is 1850?'),
    Q('his-e04', 'easy', 'Bahá\'u\'lláh passed away in this year.', 'What is 1892?'),
    Q('his-e05', 'easy', '\'Abdu\'l-Bahá passed away in this year.', 'What is 1921?'),
    Q('his-e06', 'easy', 'Shoghi Effendi passed away in this year.', 'What is 1957?'),
    Q('his-e07', 'easy', 'The first Universal House of Justice was elected in this year.', 'What is 1963?'),
    Q('his-e08', 'easy', 'In 1852, Bahá\'u\'lláh was thrown into a dark dungeon in Tehran called the Síyáh-Chál.', 'What is the Síyáh-Chál?'),
    Q('his-e09', 'easy', 'The Báb\'s remains were finally placed in His shrine on Mount Carmel in this year.', 'What is 1909?'),
    Q('his-e10', 'easy', '\'Abdu\'l-Bahá visited North America in this year.', 'What is 1912?'),
    Q('his-e11', 'easy', 'Shoghi Effendi launched a global teaching campaign called the Ten Year Crusade in this year.', 'What is 1953?'),
    Q('his-e12', 'easy', 'After the 1979 revolution, Bahá\'ís in this country faced severe persecution.', 'What is Iran?'),
    Q('his-m01', 'medium', 'At the 1848 conference of Badasht, Bábí leaders proclaimed a decisive break from traditional Islamic practice at this gathering.', 'What is Badasht?'),
    Q('his-m02', 'medium', 'The siege of Shaykh Tabarsí lasted from 1848 to this year.', 'What is 1849?'),
    Q('his-m03', 'medium', 'Bahá\'u\'lláh was banished from Baghdad to Constantinople (today Istanbul) in this year.', 'What is 1863?'),
    Q('his-m04', 'medium', 'Bahá\'u\'lláh was exiled from Adrianople to \'Akká in this year.', 'What is 1868?'),
    Q('his-m05', 'medium', 'The Young Turk Revolution in 1908 ended \'Abdu\'l-Bahá\'s decades of confinement in this region.', 'What is Palestine?'),
    Q('his-m06', 'medium', 'The first Bahá\'í National Convention in the United States was held in this city in 1909.', 'What is Chicago?'),
    Q('his-m07', 'medium', 'The Tablets of the Divine Plan were revealed by \'Abdu\'l-Bahá during this global conflict.', 'What is World War I?'),
    Q('his-m08', 'medium', 'The Hands of the Cause directed the Bahá\'í world between 1957 and the election of the Universal House of Justice in this year.', 'What is 1963?'),
    Q('his-m09', 'medium', 'The persecution of Bahá\'ís in Iran intensified after this revolution in 1979.', 'What is the Islamic Revolution?'),
    Q('his-m10', 'medium', 'The Bábí uprising at Zanján lasted from 1850 to this year.', 'What is 1851?'),
    Q('his-m11', 'medium', 'Bahá\'u\'lláh was banished from Baghdad to Constantinople (Istanbul) in this year.', 'What is 1863?'),
    Q('his-m12', 'medium', 'The first Bahá\'í pilgrimage to the Holy Land by Western believers occurred in this decade.', 'What is the 1890s?'),
    Q('his-h01', 'hard', 'The attempt on Násiri\'d-Dín Sháh\'s life on August 15, 1852, was carried out by radical Bábís, not members of this later faction led by Mírzá Yahyá.', 'What are the Azalís?'),
    Q('his-h02', 'hard', 'The conference of Badasht was held in the summer of this year.', 'What is 1848?'),
    Q('his-h03', 'hard', 'Mullá Husayn led the defense of Shaykh Tabarsí and was killed in this year.', 'What is 1849?'),
    Q('his-h04', 'hard', 'Bahá\'u\'lláh was exiled from Constantinople to Adrianople after only four months, arriving in this year.', 'What is 1863?'),
    Q('his-h05', 'hard', 'The Ottoman authorities separated Bahá\'u\'lláh from the Azalís by exiling Bahá\'u\'lláh to \'Akká and Azal to this city.', 'What is Famagusta?'),
    Q('his-h06', 'hard', 'The first contingent of Hands of the Cause was appointed by Shoghi Effendi in this year.', 'What is 1951?'),
    Q('his-h07', 'hard', 'The Universal House of Justice was elected at the International Convention in this city.', 'What is Haifa?'),
    Q('his-h08', 'hard', 'The Bahá\'í community of Russia was decimated after this political revolution in 1917.', 'What is the Russian Revolution?'),
    Q('his-h09', 'hard', 'The House of the Báb in Shiraz was designated a Bahá\'í pilgrimage site until its destruction in this year.', 'What is 1979?'),
    Q('his-h10', 'hard', 'The second International Convention in 1968 elected the Universal House of Justice for this term.', 'What is the second?'),
    Q('his-h11', 'hard', 'Táhirih was executed in 1852 in this city.', 'What is Tehran?'),
    Q('his-h12', 'hard', 'The Bábís at Nayríz were besieged in 1850 under the leadership of this believer.', 'Who is Vahíd?'),
  ],
  "BAHA'I CALENDAR": [
    Q('cal-e01', 'easy', 'The Bahá\'í New Year, Naw-Rúz, falls on the first day of spring — around March 20 or 21.', 'What is Naw-Rúz?'),
    Q('cal-e02', 'easy', 'The Bahá\'í calendar has this many months.', 'What is 19?'),
    Q('cal-e03', 'easy', 'Each month in the Bahá\'í calendar has this many days.', 'What is 19?'),
    Q('cal-e04', 'easy', 'The first month of the Bahá\'í year is named Bahá, which means "splendor" or "glory."', 'What is Bahá?'),
    Q('cal-e05', 'easy', 'The 19-day Fast happens during the last month of the year, called \'Alá.', 'What is the Fast?'),
    Q('cal-e06', 'easy', 'The Festival of Riḍván lasts twelve days and celebrates Bahá\'u\'lláh\'s declaration in 1863.', 'What is Riḍván?'),
    Q('cal-e07', 'easy', 'The Twin Holy Days celebrate the birthdays of the Báb and Bahá\'u\'lláh in October or November.', 'What are the Twin Holy Days?'),
    Q('cal-e08', 'easy', 'Ayyám-i-Há is a short festive period of 4 or 5 days right before the Fast.', 'What is Ayyám-i-Há?'),
    Q('cal-e09', 'easy', 'A Bahá\'í week has this many days, just like the Gregorian calendar.', 'What is seven?'),
    Q('cal-e10', 'easy', 'Bahá\'ís mark May 23 each year as the anniversary of the Báb\'s declaration in Shiraz.', 'What is the Declaration of the Báb?'),
    Q('cal-e11', 'easy', 'Bahá\'ís observe May 29 each year as the anniversary of Bahá\'u\'lláh\'s passing near \'Akká.', 'What is the Ascension of Bahá\'u\'lláh?'),
    Q('cal-e12', 'easy', 'Bahá\'ís observe November 28 each year as the anniversary of \'Abdu\'l-Bahá\'s passing in Haifa.', 'What is the Ascension of \'Abdu\'l-Bahá?'),
    Q('cal-m01', 'medium', 'The second month of the Bahá\'í calendar is named this.', 'What is Jalál?'),
    Q('cal-m02', 'medium', 'The month of Mulk is the 18th month; the 19th and final month before Naw-Rúz is this.', 'What is \'Alá?'),
    Q('cal-m03', 'medium', 'The Bahá\'í calendar was established by the Báb and later confirmed by this Manifestation of God.', 'Who is Bahá\'u\'lláh?'),
    Q('cal-m04', 'medium', 'The first day of Riḍván, April 21, marks the day Bahá\'u\'lláh entered this garden.', 'What is the Garden of Ridván?'),
    Q('cal-m05', 'medium', 'The ninth day of Riḍván marks when Bahá\'u\'lláh\'s family left their home in Baghdad, called the Most Great House.', 'What is the Most Great House?'),
    Q('cal-m06', 'medium', 'On the twelfth day of Riḍván, Bahá\'u\'lláh and His family departed the Garden of Ridván heading toward Constantinople, today called this.', 'What is Istanbul?'),
    Q('cal-m07', 'medium', 'The Martyrdom of the Báb is observed on July 9 at this time of day, when His execution took place.', 'What is noon?'),
    Q('cal-m08', 'medium', 'The Bahá\'í era (B.E.) begins with the year of the Báb\'s declaration in this year of the Gregorian calendar.', 'What is 1844?'),
    Q('cal-m09', 'medium', 'The month of Jamál is the third month; its name means this in Arabic.', 'What is beauty?'),
    Q('cal-m10', 'medium', 'Naw-Rúz falls on the day of the vernal equinox in this hemisphere\'s spring.', 'What is the Northern Hemisphere?'),
    Q('cal-m11', 'medium', 'The Universal House of Justice announced in 2014 that the Twin Holy Days would be celebrated on fixed dates in this calendar.', 'What is the Gregorian calendar?'),
    Q('cal-m12', 'medium', 'The month of Kalimát means "words" in Arabic and is the sixth month, corresponding roughly to this Gregorian month.', 'What is July?'),
    Q('cal-h01', 'hard', 'The Bahá\'í era (B.E.) begins in the year of the Báb\'s declaration; the year 180 B.E. falls in the 2020s of this calendar.', 'What is the Gregorian calendar?'),
    Q('cal-h02', 'hard', 'The Festival of Riḍván lasts twelve days and commemorates Bahá\'u\'lláh\'s declaration in this year.', 'What is 1863?'),
    Q('cal-h03', 'hard', 'The Martyrdom of the Báb is observed at noon on July 9, marking His execution in this year.', 'What is 1850?'),
    Q('cal-h04', 'hard', 'The Twin Holy Days celebrate the births of the Báb and Bahá\'u\'lláh, which fell on consecutive days in the Islamic calendar.', 'What are the Twin Holy Days?'),
    Q('cal-h05', 'hard', 'Ayyám-i-Há are extra days of hospitality and gift-giving inserted before this annual period of fasting.', 'What is the Fast?'),
    Q('cal-h06', 'hard', 'The first, ninth, and twelfth days of Riḍván are Holy Days when work is suspended for Bahá\'ís.', 'What is Riḍván?'),
    Q('cal-h07', 'hard', 'The Ascension of Bahá\'u\'lláh is observed on May 29, the anniversary of His passing in this year.', 'What is 1892?'),
    Q('cal-h08', 'hard', 'The Ascension of \'Abdu\'l-Bahá is observed on November 28, the anniversary of His passing in this year.', 'What is 1921?'),
    Q('cal-h09', 'hard', 'Ayyám-i-Há are devoted to hospitality, charity, and preparing spiritually for this 19-day period.', 'What is the Fast?'),
    Q('cal-h10', 'hard', 'Bahá\'í year 1 B.E. began on March 21, 1844, and ended on March 20 of this next Gregorian year.', 'What is 1845?'),
    Q('cal-h11', 'hard', 'The month of Núr, meaning "light," comes just before the month of Rahmat, which means this.', 'What is mercy?'),
    Q('cal-h12', 'hard', 'In 2015, the Universal House of Justice unified the dates of Naw-Rúz worldwide using this calendar system.', 'What is the Gregorian calendar?'),
  ],
  'HANDS OF THE CAUSE': [
    Q('hoc-e01', 'easy', 'Shoghi Effendi named a corps of distinguished believers to protect and promote the Faith—these officers were called this.', 'What are the Hands of the Cause?'),
    Q('hoc-e02', 'easy', 'Rúhíyyih Khánum, born Mary Maxwell, was the wife of Shoghi Effendi and a Hand of the Cause.', 'Who is Rúhíyyih Khánum?'),
    Q('hoc-e03', 'easy', 'Martha Root traveled the world for decades teaching the Bahá\'í Faith.', 'Who is Martha Root?'),
    Q('hoc-e04', 'easy', 'Lua Getsinger was one of the first American Bahá\'ís and a pioneering teacher.', 'Who is Lua Getsinger?'),
    Q('hoc-e05', 'easy', 'William Sutherland Maxwell, an architect, designed the Shrine of the Báb and was Rúhíyyih Khánum\'s father.', 'Who is William Sutherland Maxwell?'),
    Q('hoc-e06', 'easy', 'After Shoghi Effendi passed away in 1957, the Hands of the Cause led the Faith until this supreme body was elected in 1963.', 'What is the Universal House of Justice?'),
    Q('hoc-e07', 'easy', 'Louis Gregory, appointed in 1951, was the first African American Hand of the Cause.', 'Who is Louis Gregory?'),
    Q('hoc-e08', 'easy', 'The first group of Hands of the Cause was appointed by Shoghi Effendi in this year.', 'What is 1951?'),
    Q('hoc-e09', 'easy', 'Amatu\'l-Bahá Rúhíyyih Khánum traveled the world representing the Bahá\'í Faith after 1957.', 'Who is Rúhíyyih Khánum?'),
    Q('hoc-e10', 'easy', 'Corinne True helped establish the Bahá\'í community in Chicago and was named a Hand of the Cause.', 'Who is Corinne True?'),
    Q('hoc-e11', 'easy', 'Martha Root met with leaders like Gandhi and Queen Marie of Romania while teaching the Faith.', 'Who is Martha Root?'),
    Q('hoc-e12', 'easy', 'The Custodians—a group of nine Hands of the Cause—guided the Bahá\'í world from 1957 until this year.', 'What is 1963?'),
    Q('hoc-m01', 'medium', 'This early believer, regarded as mother of the Bahá\'í community of Canada, hosted \'Abdu\'l-Bahá in Montreal in 1912.', 'Who is May Maxwell?'),
    Q('hoc-m02', 'medium', 'Hájí Mírzá Haydar-\'Alí was a prominent Hand of the Cause during the ministry of this Central Figure.', 'Who is Bahá\'u\'lláh?'),
    Q('hoc-m03', 'medium', 'Hájí Mírzá Muhammad-Taqí Abhari, known as Ibn-i-Abhar, was appointed a Hand of the Cause by this Figure.', 'Who is Bahá\'u\'lláh?'),
    Q('hoc-m04', 'medium', 'Keith Ransom-Kehler, the first Western woman named a martyr of the Faith, died while serving in this country.', 'What is Iran?'),
    Q('hoc-m05', 'medium', 'Amelia Collins, a Hand of the Cause, donated her home on Haparsim Street in Haifa, used as this for pilgrims.', 'What is the Pilgrim House?'),
    Q('hoc-m06', 'medium', 'Dorothy Baker was a Hand of the Cause who perished in a plane crash in this year.', 'What is 1946?'),
    Q('hoc-m07', 'medium', 'George Townshend, a Hand of the Cause and noted author, was from this island nation.', 'What is Ireland?'),
    Q('hoc-m08', 'medium', 'Clara Dunn and her husband Hyde Dunn brought the Faith to this continent.', 'What is Australia?'),
    Q('hoc-m09', 'medium', 'Ella Bailey, a valiant pioneer of the Ten Year Crusade, died in 1953 while pioneering in this North African country.', 'What is Libya?'),
    Q('hoc-m10', 'medium', 'Ugo Giachery was a Hand of the Cause who supervised the construction of the superstructure of the Shrine of the Báb in this city.', 'What is Haifa?'),
    Q('hoc-m11', 'medium', 'Mason Remey was appointed a Hand of the Cause but later broke the Covenant and claimed to be this.', 'What is the second Guardian?'),
    Q('hoc-m12', 'medium', 'The Custodians, a body of nine Hands of the Cause, directed the Faith from 1957 until this year.', 'What is 1963?'),
    Q('hoc-h01', 'hard', 'Hájí Mírzá Haydar-\'Alí wrote a memoir of his pilgrimage titled "Bihjatu\'s-Sudúr," translated as this.', 'What is The Delight of Hearts?'),
    Q('hoc-h02', 'hard', 'Ibn-i-Asdaq was the first Hand of the Cause appointed by Bahá\'u\'lláh; his father was this prominent believer.', 'Who is Mullá Sádiq-i-Khurásání?'),
    Q('hoc-h03', 'hard', 'Áqá Muhammad-i-Qá\'iní, granted the title Nabíl-i-Akbar by Bahá\'u\'lláh, was appointed a Hand of the Cause posthumously by this Figure.', 'Who is \'Abdu\'l-Bahá?'),
    Q('hoc-h04', 'hard', 'Keith Ransom-Kehler died in Isfahan in 1933 after confronting Iranian authorities about the persecution of Bahá\'ís regarding this issue.', 'What is the denial of burial rights?'),
    Q('hoc-h05', 'hard', 'Amatu\'l-Bahá Rúhíyyih Khánum authored a biography of the Guardian titled this.', 'What is The Priceless Pearl?'),
    Q('hoc-h06', 'hard', 'Martha Root met with Queen Marie of this country, who became the first crowned head to embrace the Faith.', 'What is Romania?'),
    Q('hoc-h07', 'hard', 'Shoghi Effendi appointed a second contingent of Hands of the Cause in this year, shortly before his passing.', 'What is 1957?'),
    Q('hoc-h08', 'hard', 'The Hands of the Cause held a conclave in \'Akká in 1957 and determined that Shoghi Effendi had left no appointed this.', 'What is a successor Guardian?'),
    Q('hoc-h09', 'hard', 'Jalál Kházeh was a Hand of the Cause from this country who served as a physician.', 'What is Iran?'),
    Q('hoc-h10', 'hard', 'Paul Haney was appointed a Hand of the Cause by Shoghi Effendi in this year.', 'What is 1954?'),
    Q('hoc-h11', 'hard', 'Agnes Alexander brought the Bahá\'í Faith to this U.S. state and later to Japan.', 'What is Hawaii?'),
    Q('hoc-h12', 'hard', 'The institution of Continental Boards of Counsellors was established in 1968 to extend the work of the Hands of the Cause in this capacity.', 'What is propagation and protection?'),
  ],
  'INSTITUTIONS': [
    Q('ins-e01', 'easy', 'The supreme governing body of the Bahá\'í Faith, elected every five years in Haifa, is this.', 'What is the Universal House of Justice?'),
    Q('ins-e02', 'easy', 'Local Bahá\'í communities elect a nine-member governing body called a Local Spiritual Assembly.', 'What is a Local Spiritual Assembly?'),
    Q('ins-e03', 'easy', 'Each country\'s Bahá\'í community elects a National Spiritual Assembly each year during Riḍván.', 'What is a National Spiritual Assembly?'),
    Q('ins-e04', 'easy', 'Bahá\'í elections have no campaigning — voters choose based on a person\'s character and service.', 'What is a Bahá\'í election?'),
    Q('ins-e05', 'easy', 'The Universal House of Justice sits on Mount Carmel in this city.', 'What is Haifa?'),
    Q('ins-e06', 'easy', 'Bahá\'ís gather every 19 days for a community meeting called a Feast, with devotional, consultative, and social parts.', 'What is the Nineteen Day Feast?'),
    Q('ins-e07', 'easy', 'Bahá\'ís make important decisions through group discussion and prayer called this.', 'What is consultation?'),
    Q('ins-e08', 'easy', 'There is no clergy in the Bahá\'í Faith — leadership comes from elected assemblies.', 'What is a Spiritual Assembly?'),
    Q('ins-e09', 'easy', 'The Bahá\'í International Community represents the Faith at the United Nations.', 'What is the Bahá\'í International Community?'),
    Q('ins-e10', 'easy', 'Nine members are elected to each Local and National Spiritual Assembly.', 'What is nine?'),
    Q('ins-e11', 'easy', 'The first Universal House of Justice was elected in this year.', 'What is 1963?'),
    Q('ins-e12', 'easy', 'Bahá\'í Houses of Worship are open to people of all faiths for prayer and reflection.', 'What is a House of Worship?'),
    Q('ins-m01', 'medium', 'The Universal House of Justice was first elected in 1963 at the International Convention in this city.', 'What is Haifa?'),
    Q('ins-m02', 'medium', 'Continental Boards of Counsellors were established in 1968 to succeed the institution of Hands of the Cause in this function.', 'What is propagation and protection?'),
    Q('ins-m03', 'medium', 'The Institution of the Counsellors operates under the direction of this body.', 'What is the Universal House of Justice?'),
    Q('ins-m04', 'medium', 'Before a community can elect a Local Spiritual Assembly, at least nine adult Bahá\'ís must live in the same area.', 'What is a Local Spiritual Assembly?'),
    Q('ins-m05', 'medium', 'The National Spiritual Assembly of the Bahá\'ís of the United States is based near Chicago in this suburb.', 'What is Evanston?'),
    Q('ins-m06', 'medium', 'The Huqúqu\'lláh, a spiritual obligation of giving, is administered by this institution.', 'What is the Institution of Huqúqu\'lláh?'),
    Q('ins-m07', 'medium', 'The Bahá\'í International Community has consultative status with ECOSOC, a body of this organization.', 'What is the United Nations?'),
    Q('ins-m08', 'medium', 'The Arc on Mount Carmel includes the Seat of the Universal House of Justice, the International Teaching Centre, and this building.', 'What is the Centre for the Study of the Texts?'),
    Q('ins-m09', 'medium', 'Bahá\'í elections require that voters consider only this quality in candidates.', 'What is merit?'),
    Q('ins-m10', 'medium', 'The Auxiliary Board members are appointed by Continental Counsellors to assist Local and National Spiritual Assemblies in this work.', 'What is teaching and protection?'),
    Q('ins-m11', 'medium', 'The Bahá\'í Faith has no individual leaders at the local level; decisions are made through this process.', 'What is consultation?'),
    Q('ins-m12', 'medium', 'The Seat of the Universal House of Justice was completed in this year.', 'What is 1983?'),
    Q('ins-h01', 'hard', 'The Universal House of Justice is elected by members of National Spiritual Assemblies at the International Convention held every this many years.', 'What is five?'),
    Q('ins-h02', 'hard', 'The Institution of Huqúqu\'lláh was formally established by the Universal House of Justice in this year.', 'What is 1992?'),
    Q('ins-h03', 'hard', 'The Bahá\'í administrative order is described by Shoghi Effendi as the nucleus and pattern of this future institution.', 'What is the World Commonwealth of Bahá\'u\'lláh?'),
    Q('ins-h04', 'hard', 'The International Teaching Centre Building on the Arc was completed in this year.', 'What is 2000?'),
    Q('ins-h05', 'hard', 'The Centre for the Study of the Texts was established to prepare translations and provide scholarly support to this body.', 'What is the Universal House of Justice?'),
    Q('ins-h06', 'hard', 'The Bahá\'í International Community\'s Office in New York was established to represent the Faith at this organization.', 'What is the United Nations?'),
    Q('ins-h07', 'hard', 'The first Local Spiritual Assembly in North America was elected in this city in 1899.', 'What is Chicago?'),
    Q('ins-h08', 'hard', 'The Guardianship and Hands of the Cause were appointed; Local and National Spiritual Assemblies, by contrast, are formed through this process each Riḍván.', 'What is a Bahá\'í election?'),
    Q('ins-h09', 'hard', 'The Universal House of Justice\'s first message to the Bahá\'í world was dated Ridván of this year.', 'What is 1963?'),
    Q('ins-h10', 'hard', 'The Bahá\'í Faith\'s system of governance is described as unique because it has no clergy and combines democratic election with this principle.', 'What is divine guidance?'),
    Q('ins-h11', 'hard', 'The Department of the Secretariat at the World Centre supports the work of this institution.', 'What is the Universal House of Justice?'),
    Q('ins-h12', 'hard', 'The Bahá\'í administrative order was described by Shoghi Effendi as the "child" of this Covenant.', 'What is the Covenant of Bahá\'u\'lláh?'),
  ],
  'PERSECUTION & RESILIENCE': [
    Q('per-e01', 'easy', 'Thousands of early Bábís were killed in 19th-century Iran because of their beliefs.', 'What is persecution?'),
    Q('per-e02', 'easy', 'More than 20,000 early followers were martyred in waves of persecution in this country.', 'What is Iran?'),
    Q('per-e03', 'easy', 'The Báb was executed by firing squad in Tabriz in this year.', 'What is 1850?'),
    Q('per-e04', 'easy', 'Táhirih, a courageous poet and scholar, was executed for her belief in the Báb.', 'Who is Táhirih?'),
    Q('per-e05', 'easy', 'In Iran today, Bahá\'í teenagers often learn they will not be allowed to attend this after high school because of their faith.', 'What is university?'),
    Q('per-e06', 'easy', 'In 2006, Iranian authorities bulldozed the Golestan Javid cemetery in Tehran—a sacred Bahá\'í burial ground in this city.', 'What is Tehran?'),
    Q('per-e07', 'easy', 'Iranian Bahá\'ís have repeatedly gone to court seeking the right to bury loved ones according to Bahá\'í law—rights known as these.', 'What are burial rights?'),
    Q('per-e08', 'easy', 'When Bahá\'ís in Iran are arrested or harassed, their response has consistently been calm dignity rather than retaliation.', 'What is steadfastness?'),
    Q('per-e09', 'easy', 'In 1983, ten Bahá\'í women were hanged in this Iranian city for refusing to renounce their faith.', 'What is Shiraz?'),
    Q('per-e10', 'easy', 'Bahá\'ís respond to persecution with dignity, patience, and commitment to this principle.', 'What is non-violence?'),
    Q('per-e11', 'easy', 'The Bahá\'í Faith is the largest religious minority in this country, where it began.', 'What is Iran?'),
    Q('per-e12', 'easy', 'Early Bábís faced torture and death rather than deny their belief in the Báb and Bahá\'u\'lláh.', 'What is martyrdom?'),
    Q('per-m01', 'medium', 'In 1983, ten Bahá\'í women in Shiraz were executed for refusing to give up their faith; the youngest was 17-year-old Mona Mahmudnizhad from this city.', 'Who is Mona Mahmudnizhad?'),
    Q('per-m02', 'medium', 'Mona Mahmudnizhad was a 17-year-old Bahá\'í girl executed in Shiraz in this year.', 'What is 1983?'),
    Q('per-m03', 'medium', 'The Bahá\'í Institute for Higher Education, known as BIHE, operates underground to provide education in this country.', 'What is Iran?'),
    Q('per-m04', 'medium', 'In 2008, seven Bahá\'í leaders in Iran, known as the Yaran, were arrested and sentenced to this.', 'What is 20 years imprisonment?'),
    Q('per-m05', 'medium', 'Hájí Mírzá Haydar-\'Alí endured imprisonment and exile for his faith during the ministry of Bahá\'u\'lláh in this prison city.', 'What is \'Akká?'),
    Q('per-m06', 'medium', 'Keith Ransom-Kehler died in this city in 1933 after confronting authorities about the denial of burial rights to Bahá\'ís.', 'What is Isfahan?'),
    Q('per-m07', 'medium', 'The siege of Shaykh Tabarsí lasted from October 1848 to May of this year.', 'What is 1849?'),
    Q('per-m08', 'medium', 'Quddús participated in the siege of Shaykh Tabarsí but was killed later in 1849 in this city (Bárfurúsh).', 'What is Barfurúsh?'),
    Q('per-m09', 'medium', 'The Bábí defenders of Zanján held out for months under the leadership of Hujjat before being overwhelmed in this year.', 'What is 1851?'),
    Q('per-m10', 'medium', 'Bahá\'u\'lláh\'s imprisonment in the Síyáh-Chál in 1852 lasted this many months.', 'What is four months?'),
    Q('per-m11', 'medium', 'The 1991 Golpaygani Memorandum, leaked to the UN, outlined Iran\'s policy to block the progress of this religious minority.', 'What is the Bahá\'í Faith?'),
    Q('per-m12', 'medium', 'Bahá\'í properties in Iran, including holy places and cemeteries, have been confiscated by this government.', 'What is the Islamic Republic of Iran?'),
    Q('per-h01', 'hard', 'The attempt on Násiri\'d-Dín Sháh\'s life in 1852 was falsely attributed to Bahá\'u\'lláh, leading to the execution of many Bábís including this woman.', 'Who is Táhirih?'),
    Q('per-h02', 'hard', 'Mullá Husayn was killed at Shaykh Tabarsí on February 2 of this year.', 'What is 1849?'),
    Q('per-h03', 'hard', 'The seven martyrs of Tehran were executed on February 2, 1850, at the order of this prime minister.', 'Who is Mírzá Taqí Khán (the Amír-Nizám)?'),
    Q('per-h04', 'hard', 'Hujjat was killed during the siege of Zanján in this year.', 'What is 1851?'),
    Q('per-h05', 'hard', 'Vahíd led the Bábí defense at Nayríz and was killed in this year.', 'What is 1850?'),
    Q('per-h06', 'hard', 'The Bahá\'í community in Turkmenistan suffered persecution after the Soviet seizure of the Mashriqu\'l-Adhkár in this city.', 'What is \'Ishqábád?'),
    Q('per-h07', 'hard', 'In 1955, anti-Bahá\'í riots in this country were incited by a cleric named Mírzá Mahmúd Falsafí.', 'What is Iran?'),
    Q('per-h08', 'hard', 'The Yaran, or Friends, were seven Bahá\'í leaders arrested in 2008; their longest sentence was this many years.', 'What is 20?'),
    Q('per-h09', 'hard', 'Bahá\'í cemeteries in Iran, including the Golestan Javid cemetery in Tehran, have been bulldozed as part of this government policy.', 'What is the eradication of the Bahá\'í community?'),
    Q('per-h10', 'hard', 'The Bahá\'í community\'s response to persecution in Iran has been guided by principles of non-violence and obedience to government except when it conflicts with this.', 'What is their faith?'),
    Q('per-h11', 'hard', 'Siyyid Ismá\'íl of Zavárih, titled Jináb-i-Básir, was executed in Baghdad in 1852 during anti-Bábí violence following this event.', 'What is the attempt on Násiri\'d-Dín Sháh\'s life?'),
    Q('per-h12', 'hard', 'The Universal House of Justice has appealed to world leaders and the UN regarding the persecution of Bahá\'ís, emphasizing that this right must be upheld.', 'What is freedom of religion?'),
  ],
};

const FINAL_JEOPARDY_POOL = [
  { id: 'fin-01', d: 'medium', category: "BAHA'I CALENDAR", clue: 'This 19-day period of fasting ends at sunset before the Bahá\'í New Year, Naw-Rúz.', answer: 'What is the Fast?' },
  { id: 'fin-02', d: 'easy', category: 'THE BÁB', clue: 'On May 23, 1844, in Shiraz, a young merchant declared He was the Promised One of Islam—a day Bahá\'ís celebrate as this holy day.', answer: 'What is the Declaration of the Báb?' },
  { id: 'fin-03', d: 'medium', category: "BAHÁ'U'LLÁH", clue: 'In 1863, Bahá\'u\'lláh declared His mission in a garden outside Baghdad during a twelve-day festival known as this.', answer: 'What is Riḍván?' },
  { id: 'fin-04', d: 'hard', category: "'ABDU'L-BAHÁ", clue: 'During World War I, \'Abdu\'l-Bahá revealed letters mapping out the teaching of the Faith on every continent, collectively known as this.', answer: 'What is the Tablets of the Divine Plan?' },
  { id: 'fin-05', d: 'medium', category: 'HOLY PLACES', clue: 'Bahá\'u\'lláh spent His final years at the Mansion of Bahjí, near this prison city on the Mediterranean.', answer: 'What is \'Akká?' },
  { id: 'fin-06', d: 'hard', category: 'THE WRITINGS', clue: 'Bahá\'u\'lláh\'s Kitáb-i-Íqán explains the continuity of religion and is subtitled "The Book of" this.', answer: 'What is Certitude?' },
  { id: 'fin-07', d: 'easy', category: 'PRINCIPLES & TEACHINGS', clue: 'Bahá\'u\'lláh compared the great Faiths of history to chapters in a single book, teaching the oneness of this.', answer: 'What is religion?' },
  { id: 'fin-08', d: 'medium', category: 'SHOGHI EFFENDI', clue: 'Shoghi Effendi launched a global teaching plan in 1953 known as the Ten Year this.', answer: 'What is the Crusade?' },
  { id: 'fin-09', d: 'hard', category: 'HISTORY & EVENTS', clue: 'In 1852, an attempt on the life of Násiri\'d-Dín Sháh led to Bahá\'u\'lláh\'s imprisonment in the Síyáh-Chál, meaning this.', answer: 'What is the Black Pit?' },
  { id: 'fin-10', d: 'medium', category: 'HANDS OF THE CAUSE', clue: 'This Hand of the Cause traveled the world, interviewed Gandhi and Queen Marie of Romania, and taught the Faith in dozens of countries.', answer: 'Who is Martha Root?' },
  { id: 'fin-11', d: 'easy', category: 'INSTITUTIONS', clue: 'The supreme governing body of the Bahá\'í Faith, elected every five years in Haifa, is called this.', answer: 'What is the Universal House of Justice?' },
  { id: 'fin-12', d: 'hard', category: 'PERSECUTION & RESILIENCE', clue: 'In 1983, ten Bahá\'í women in Shiraz were executed for refusing to renounce their faith; the youngest was only 17 years old.', answer: 'Who is Mona Mahmudnizhad?' },
  { id: 'fin-13', d: 'medium', category: 'THE BÁB', clue: 'The Báb\'s remains were secretly transported for decades before being interred on Mount Carmel in this year.', answer: 'What is 1909?' },
  { id: 'fin-14', d: 'hard', category: "BAHÁ'U'LLÁH", clue: 'In 1891, Bahá\'u\'lláh revealed a tablet on Mount Carmel designating it as the spiritual and administrative center of this world religion.', answer: 'What is the Bahá\'í Faith?' },
  { id: 'fin-15', d: 'easy', category: 'HOLY PLACES', clue: 'The golden-domed Shrine of the Báb, one of the holiest sites in the Bahá\'í world, stands on this mountain in Haifa.', answer: 'What is Mount Carmel?' },
  { id: 'fin-16', d: 'medium', category: 'PRINCIPLES & TEACHINGS', clue: 'Bahá\'u\'lláh taught that humanity is currently in its collective stage of this, the final stage before maturity.', answer: 'What is adolescence?' },
  { id: 'fin-17', d: 'hard', category: 'INSTITUTIONS', clue: 'Shoghi Effendi described the Bahá\'í administrative order as the nucleus and pattern of this future world institution.', answer: 'What is the World Commonwealth of Bahá\'u\'lláh?' },
  { id: 'fin-18', d: 'medium', category: 'HISTORY & EVENTS', clue: 'The first Universal House of Justice was elected at the International Convention in Haifa in this year.', answer: 'What is 1963?' },
];
