#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const revision = Number(execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim());
const commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
const built = new Date().toISOString();

const output = `// Auto-generated by scripts/generate-version.js — do not edit manually
window.APP_VERSION = {
  revision: ${revision},
  commit: '${commit}',
  built: '${built}'
};
`;

const outPath = path.join(__dirname, '..', 'version.js');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath} (revision ${revision}, ${commit})`);
