#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Prefer the commit being built (Cloudflare Pages / GitHub Actions) so the
// welcome-screen hash matches the deployment, not a stale committed version.js.
const fullSha =
  process.env.CF_PAGES_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  null;

let revision;
let commit;
if (fullSha) {
  commit = fullSha.slice(0, 7);
  revision = Number(
    execSync(`git rev-list --count ${fullSha}`, { encoding: 'utf8' }).trim()
  );
} else {
  revision = Number(execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim());
  commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
}
const built = new Date().toISOString();

const output = `// Auto-generated by scripts/generate-version.js — do not edit manually
window.APP_VERSION = {
  revision: ${revision},
  commit: '${commit}',
  built: '${built}'
};
`;

const outPath = path.join(__dirname, '..', 'version.js');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath} (revision ${revision}, ${commit})`);
